[package]
name = "spark_rust"
version = "0.1.0"
authors = ["Marcos <p000marcolima@prservicos.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hdfs = "0.0.4"
